name: Demo Command Injection

permissions:
    actions: write # Necessary to cancel workflow executions
    checks: write # Necessary to write reports
    pull-requests: write # Necessary to comment on PRs
    contents: read

on:
    issues: 

env:
    DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

jobs:
    testscript:
      runs-on: ubuntu-latest
      steps:
        - name: Trigger deriv-app smoke tests from regentmarkets
          env:
            test_env: ${{github.event.issue.body}}
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.E2E_WORKFLOW_TOKEN }}
            script: |
              console.log(process.env.test_env)
              
    test_injection:
      runs-on: ubuntu-latest
      steps:
        - name: Trigger deriv-app smoke tests from regentmarkets
          env:
            test_env: ${{github.event.issue.body}}
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.E2E_WORKFLOW_TOKEN }}
            script: |
              console.log("${{ env.test_env }}")
