name: Demo Command Injection

on:
    issues: 

env:
    DEMO_SECRET: ${{ secrets.DEMO_SECRET }}

jobs:
    demo-fix:
      runs-on: ubuntu-latest
      steps:
        - name: Demo Fix Injection
          env:
            test_env: ${{github.event.issue.body}}
          uses: actions/github-script@v6
          with:
            script: |
              console.log(process.env.test_env)
              
    test_injection:
      runs-on: ubuntu-latest
      steps:
        - name: Demo Injection
          env:
            test_env: ${{github.event.issue.body}}
          uses: actions/github-script@v6
          with:
            script: |
              console.log("${{ env.test_env }}")
